<a href="https://colab.research.google.com/github/Anithagayathri1/NUMPY-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a[1]

2

In [ ]:
import numpy as np
import sys

In [ ]:
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [ ]:
array=np.arange(1000)
print(array.size*array.itemsize)

8000


In [ ]:
import numpy as np
import time
size=1000000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=[(x+y)for x,y in zip(l1,l2)]
print("python list:",(time.time()-start)*1000)

python list: 124.77517127990723


In [ ]:
import numpy as np
import time
size=1000000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=a1+a2
print("numpy list:",(time.time()-start)*1000)

numpy list: 9.733915328979492


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a.ndim

2

In [ ]:
a.itemsize

8

In [ ]:
a.shape

(3, 2)

In [ ]:
a.size

6

In [ ]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.int32)

In [ ]:
a.itemsize

4

In [ ]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)

In [ ]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.int32)
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [ ]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
a.ravel()

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [ ]:
a.min()

1

In [ ]:
a.max()

6

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
np.std(a)

1.707825127659933

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)

array([ 9, 12])

In [ ]:
a.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
import numpy as np

In [ ]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
result=np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [ ]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [ ]:
c=np.arange(50).reshape(5,10)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
np.hsplit(c,10)

[array([[ 0],
        [10],
        [20],
        [30],
        [40]]),
 array([[ 1],
        [11],
        [21],
        [31],
        [41]]),
 array([[ 2],
        [12],
        [22],
        [32],
        [42]]),
 array([[ 3],
        [13],
        [23],
        [33],
        [43]]),
 array([[ 4],
        [14],
        [24],
        [34],
        [44]]),
 array([[ 5],
        [15],
        [25],
        [35],
        [45]]),
 array([[ 6],
        [16],
        [26],
        [36],
        [46]]),
 array([[ 7],
        [17],
        [27],
        [37],
        [47]]),
 array([[ 8],
        [18],
        [28],
        [38],
        [48]]),
 array([[ 9],
        [19],
        [29],
        [39],
        [49]])]

In [ ]:
b=a>6
b

array([[False, False, False, False, False, False, False,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [ ]:
a[b]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29])

In [ ]:
a[b]=-1
a

array([[ 0,  1,  2,  3,  4,  5,  6, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])