<a href="https://colab.research.google.com/github/Anithagayathri1/NUMPY-/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#argmax,argmin

In [ ]:
import numpy as np

In [ ]:
var=np.array([22,43,14,55,45])
var

array([22, 43, 14, 55, 45])

In [ ]:
var.max()

55

In [ ]:
var.argmax()

3

In [ ]:
var.min()

14

In [ ]:
var.argmin()

2

#Transpose

In [ ]:
r=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
t=r.T
t

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

#Floor and ceill

In [ ]:
arr=np.array([10.3,3.42,5.6,1,8,2.3])
arr

array([10.3 ,  3.42,  5.6 ,  1.  ,  8.  ,  2.3 ])

In [ ]:
np.floor(arr)

array([10.,  3.,  5.,  1.,  8.,  2.])

In [ ]:
np.round(arr)

array([10.,  3.,  6.,  1.,  8.,  2.])

In [ ]:
np.ceil(arr)

array([11.,  4.,  6.,  1.,  8.,  3.])