<a href="https://colab.research.google.com/github/Anithagayathri1/NUMPY-/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#version


In [ ]:
print(np.__version__)

1.26.4


#creation of arrays can be done in 4 different methods that are:
# array(),asarray()with nditer(),frombuffer(),fromiter()

# #0 dimensional array using array()

In [ ]:
#creation of arrays can be done in 4 different methods that are:
# array(),asarray()with nditer(),frombuffer(),fromiter()

#0 dimensional array using array()
a=np.array(10)
a

array(10)

#1dimesional array using array()

In [ ]:
#1 dimensional array
a=np.array([10,20,30])
a

array([10, 20, 30])

#2 dimensional array using array()

In [ ]:
#2 dimensional array
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

#to know the dimension using ndim

---




In [ ]:
# to know the dimension of a particular array we use ndim
a.ndim

2

#accesing of 2 dim array using numpy

In [ ]:
#accesing of 2 dimensional array in numpy
a[1][0]

30

In [ ]:
a[0][0]

10

In [ ]:
a[0][1]

20

In [ ]:
a[1][1]

40

In [ ]:
a[1][2]#it gets error because there is no element present in the given index

IndexError: index 2 is out of bounds for axis 0 with size 2

#3 dimensional array using array()

In [ ]:
# 3 dimensional array
b=np.array([[[1,2],[3,4],[5,6]]])
b.ndim

3

#accessing 3 dim array

In [ ]:
#accessing of 3 dimensional array
b[0][2][1]

6

In [ ]:
b[0][3][0]

IndexError: index 3 is out of bounds for axis 0 with size 3

#creation of array using asarray() with nditer

In [ ]:
#creation of array using asarray() with nditer()
a=[1,2,3,4]
b=np.asarray(a,dtype=float)

In [ ]:
print(b)

[1. 2. 3. 4.]


In [ ]:
a=[[1,2,3,4],[10,20,30,40]]
b=np.asarray(a,dtype=int,order='C')#order='c'(row major order)


In [ ]:
print(b)

[[ 1  2  3  4]
 [10 20 30 40]]


In [ ]:
for i in np.nditer(b):
  print(i)

1
2
3
4
10
20
30
40


In [ ]:
a=[[1,2,3,4],[10,20,30,40]]
b=np.asarray(a,dtype=int,order='F')#order='F'(column major order)



In [ ]:
print(b)

[[ 1  2  3  4]
 [10 20 30 40]]


In [ ]:
for i in np.nditer(b):
   print(i)


1
10
2
20
3
30
4
40


#creation of array by using frombuffer()

In [ ]:
#creation of array by using frombuffer()
a=b"Welcome to Numpy"

In [ ]:
np.frombuffer(a,dtype="S1",count=3,offset=9)


array([b'o', b' ', b'N'], dtype='|S1')

In [ ]:
a=[10,20,30,40,50]


#creation of array by using fromiter()

In [ ]:
np.fromiter(a,dtype=float,count=3)

array([10., 20., 30.])

In [ ]:
np.fromiter(a,dtype=float,count=4)

array([10., 20., 30., 40.])

In [ ]:
np.fromiter(a,dtype="S1",count=5)

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

#initializing array
-->zeroes()
-->full()
-->random.rand()
-->ones()
-->eye()
-->//numericalranges//<--
-->arange()
-->linspace()
-->logspace()

In [ ]:
a=np.zeros(3)#zeros()


In [ ]:
print(a)

[0. 0. 0.]


In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros([2,3])#means 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros([2,3,3])#means 2 layers 3 rows 3 columns

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.full([2,3],1)#full()

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full([3,5],2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [ ]:
np.full([2,3,4],10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [ ]:
np.random.rand(2,3)#random.rand()

array([[0.15286653, 0.04730228, 0.50720644],
       [0.64977038, 0.06607403, 0.90432764]])

In [ ]:
np.random.rand(2,3,4)

array([[[0.92000806, 0.72756062, 0.60648262, 0.86683393],
        [0.61332505, 0.53494771, 0.09908314, 0.76923214],
        [0.80035745, 0.33501282, 0.15517698, 0.43403229]],

       [[0.94756499, 0.93436483, 0.22461877, 0.0316392 ],
        [0.66748709, 0.00295091, 0.10236009, 0.42771712],
        [0.20077484, 0.15302026, 0.95444628, 0.33120848]]])

In [ ]:
np.ones(2)#ones()

array([1., 1.])

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.eye(2)#eye()#diagonal of a matrix is 1 remaining zeroes

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Numerical Ranges
1.arange()  2.linspace() 3.logspace()

In [ ]:
np.arange(10,20,1,dtype=float)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [ ]:
np.arange(0,100,20,dtype=int)

array([ 0, 20, 40, 60, 80])

#Array Operations
1.Accessing and slicing operations
2.copy()
3.view()
4.sort()
5.reshape()
6.append()
7.insert()
8.delete()
9.concatenate()
10.stack()
11.vstack()
12.hstack()
13.dstack()
14.split()
15.where()
16.searchsorted()

In [ ]:
a=np.arange(10,70,10)#arange()
a

array([10, 20, 30, 40, 50, 60])

In [ ]:
a.reshape(2,3)#reshape() is used to divide the array with rows and columns here there is 2 rows and 3 columns

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
a.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
a.reshape(6,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [ ]:
np.linspace(10,100,10)#linspace(start,stop,no.of intervals)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(0,100,20,endpoint=False,retstep=True)

(array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
        65., 70., 75., 80., 85., 90., 95.]),
 5.0)

In [ ]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [ ]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

#Array properties
--->SIZE-np.size(array)
--->SHAPE-np.shape(array)
--->DTYPE-np.dtype(array)

In [ ]:
a=np.arange(10,100,10)#array initialization using arange()
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a=a.reshape(3,3)#reshape of the array
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.size(a)#size of the array

9

In [ ]:
np.shape(a)#shape of the array

(3, 3)

In [ ]:
a.dtype#datatype of the array

dtype('int64')

In [ ]:
b=np.array([10,20,30],dtype=float)
b

array([10., 20., 30.])

In [ ]:
b.size

3

In [ ]:
b.shape

(3,)

In [ ]:
b.dtype

dtype('float64')

#Array operations
Note:array operations are given above

In [ ]:
#accessing
a=np.array([[10,20,30],[1,2,3]])
a


array([[10, 20, 30],
       [ 1,  2,  3]])

In [ ]:
a[0]

array([10, 20, 30])

In [ ]:
a[1]

array([1, 2, 3])

In [ ]:
a[0][1]

20

In [ ]:
a[1][2]

3

In [ ]:
#slicing
s=np.arange(10,100,10)
s

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
s[1:3]

array([20, 30])

In [ ]:
s[2:5]

array([30, 40, 50])

In [ ]:
#copy()
s1=np.array([[10,20,30],[2,3,4]])
s1

array([[10, 20, 30],
       [ 2,  3,  4]])

In [ ]:
s2=np.copy(s1)#copy()
s2

array([[10, 20, 30],
       [ 2,  3,  4]])

In [ ]:
s1[1][2]=300
s1

array([[ 10,  20,  30],
       [  2,   3, 300]])

In [ ]:
s2

array([[10, 20, 30],
       [ 2,  3,  4]])

In [ ]:
#view() is similar to copy but it acts as only reference
s3=s2.view()
s3

array([[10, 20, 30],
       [ 2,  3,  4]])

In [ ]:
s2[1][1]=100
s2

array([[ 10,  20,  30],
       [  2, 100,   4]])

In [ ]:
s3

array([[ 10,  20,  30],
       [  2, 100,   4]])

In [ ]:
#sort()
a=np.array([10,30,20,40,80,60])
a=np.sort(a)
a

array([10, 20, 30, 40, 60, 80])

In [ ]:
#reshape()
a=a.reshape(3,2)
a

array([[10, 20],
       [30, 40],
       [60, 80]])

In [ ]:
b=np.array([[40,10,20],[2,1,3]])
np.sort(b)#row sorting


array([[10, 20, 40],
       [ 1,  2,  3]])

In [ ]:
b

array([[40, 10, 20],
       [ 2,  1,  3]])

In [ ]:
np.sort(b,axis=0)#column sorting

array([[ 2,  1,  3],
       [40, 10, 20]])

In [ ]:
np.sort(b,axis=1)#row sorting

array([[10, 20, 40],
       [ 1,  2,  3]])

In [ ]:
d=np.dtype([('name','S1'),('perc',float)])

In [ ]:
marks=np.array([("siri",95.8),("kranthi",90.8),("zohn",89.8)],dtype=d)
marks

array([(b's', 95.8), (b'k', 90.8), (b'z', 89.8)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="perc")

array([(b'z', 89.8), (b'k', 90.8), (b's', 95.8)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="name")

array([(b'k', 90.8), (b's', 95.8), (b'z', 89.8)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
a=np.arange(10,110,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
a.reshape(2,5)#reshape()

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [ ]:
a=np.arange(10,130,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [ ]:
a.reshape(3,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [ ]:
a.reshape(2,3,2)

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]]])

In [ ]:
#append()
a=np.array([10,20,30])
b=np.array([40,50,60])

In [ ]:
np.append(a,b)

array([10, 20, 30, 40, 50, 60])

In [ ]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3],[4,5,6]])

In [ ]:
np.append(a,b).reshape(4,3)

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
c=np.array([10,20,30])

In [ ]:
#insert()
np.insert(c,2,35)

array([10, 20, 35, 30])

In [ ]:
c

array([10, 20, 30])

In [ ]:
np.insert(c,3,[40,45])

array([10, 20, 30, 40, 45])

In [ ]:
c=np.array([[10,20,30],[40,50,60]])
c

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.insert(c,6,[70,80]).reshape(4,2)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
#delete()
a

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.delete(a,2)

array([10, 20, 40, 50, 60])

In [ ]:
np.delete(a,[2,3])

array([10, 20, 50, 60])

In [ ]:
#concatenate()
a=np.array([[10,20,30],[1,2,3]])
b=np.array([[40,50,60],[4,5,6]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[10, 20, 30, 40, 50, 60],
       [ 1,  2,  3,  4,  5,  6]])

In [ ]:
np.concatenate((a,b))

array([[10, 20, 30],
       [ 1,  2,  3],
       [40, 50, 60],
       [ 4,  5,  6]])

In [ ]:
a

array([[10, 20, 30],
       [ 1,  2,  3]])

In [ ]:
b

array([[40, 50, 60],
       [ 4,  5,  6]])

In [ ]:
#stack()
np.stack((a,b))
#np.concatenate((a,b))

array([[[10, 20, 30],
        [ 1,  2,  3]],

       [[40, 50, 60],
        [ 4,  5,  6]]])

In [ ]:
np.stack((a,b),axis=1)

array([[[10, 20, 30],
        [40, 50, 60]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [ ]:
#vstack()
np.vstack((a,b))

array([[10, 20, 30],
       [ 1,  2,  3],
       [40, 50, 60],
       [ 4,  5,  6]])

In [ ]:
#hstack()
np.hstack((a,b))

array([[10, 20, 30, 40, 50, 60],
       [ 1,  2,  3,  4,  5,  6]])

In [ ]:
a

array([[10, 20, 30],
       [ 1,  2,  3]])

In [ ]:
b

array([[40, 50, 60],
       [ 4,  5,  6]])

In [ ]:
#dstack()
np.dstack((a,b))

array([[[10, 40],
        [20, 50],
        [30, 60]],

       [[ 1,  4],
        [ 2,  5],
        [ 3,  6]]])

In [ ]:
#split()
x=np.arange(10,110,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.split(x,2)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [ ]:
z=np.split(x,5)

In [ ]:
z

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

In [ ]:
s1,s2,s3,s4,s5=z

In [ ]:
s1

array([10, 20])

In [ ]:
s2

array([30, 40])

In [ ]:
x=np.arange(10,130,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [ ]:
np.split(x,(2,6))

[array([10, 20]),
 array([30, 40, 50, 60]),
 array([ 70,  80,  90, 100, 110, 120])]

In [ ]:
#where()-->it checks a particular element is present or not
a=np.arange(10,130,10).reshape(4,3)
a


array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
np.where(a==80)

(array([2]), array([1]))

In [ ]:
np.where(a>80)

(array([2, 3, 3, 3]), array([2, 0, 1, 2]))

In [ ]:
b=np.arange(10,110,10).reshape(5,2)
b

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [ ]:
np.where((b==80,b==90))#through value

(array([0, 1]), array([3, 4]), array([1, 0]))

In [ ]:
np.where(b%20==0)#through expression

(array([0, 1, 2, 3, 4]), array([1, 1, 1, 1, 1]))

In [ ]:
a=np.array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [ ]:
#searchsorted()
np.searchsorted(a,20)

1

In [ ]:
np.searchsorted(a,50)

4

In [ ]:
np.searchsorted(a,[40,50])

array([3, 4])

#Arithmetic operations
1.add()
2.subtract()
3.Multiply()
4.Divide()
5.Exp()
6.Sqrt()
note:for performing arithmetic operations dimensions should be equal,
no of elements should be equal

In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3],[4,5,6]])

In [ ]:
a,b

(array([[10, 20, 30],
        [40, 50, 60]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66]])

In [ ]:
c=np.array([[10,20],[30,40]])
np.add(a,c)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
np.subtract(a,b)

array([[ 9, 18, 27],
       [36, 45, 54]])

In [ ]:
np.subtract(b,a)

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [ ]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [ ]:
np.divide(a,b)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
a,b

(array([[10, 20, 30],
        [40, 50, 60]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
np.exp(a),np.exp(b)

(array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
        [2.35385267e+17, 5.18470553e+21, 1.14200739e+26]]),
 array([[  2.71828183,   7.3890561 ,  20.08553692],
        [ 54.59815003, 148.4131591 , 403.42879349]]))

In [ ]:
np.sqrt(a),np.sqrt(b)

(array([[3.16227766, 4.47213595, 5.47722558],
        [6.32455532, 7.07106781, 7.74596669]]),
 array([[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]))

#Comparision operator


In [ ]:
a,b

(array([[10, 20, 30],
        [40, 50, 60]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
b[0][1]

2

In [ ]:
#changing of values
b[1][0]=40
b[1][1]=50
b[1][2]=60
b

array([[ 1,  2,  3],
       [40, 50, 60]])

In [ ]:
#by compare array wise comparision we have one function called array_equal(a,b)
np.array_equal(a,b)

False

In [ ]:
a,b

(array([[10, 20, 30],
        [40, 50, 60]]),
 array([[ 1,  2,  3],
        [40, 50, 60]]))

In [ ]:
#by element wise comparision
a==b

array([[False, False, False],
       [ True,  True,  True]])

#Array Functions
1.sum()
2.min()
3.max()
4.mean()
5.median()
6.var()
7.std()


In [ ]:
a=np.array([[10,20],[30,40],[50,60]])
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
np.min(a)

10

In [ ]:
np.min(a,axis=1)

array([10, 30, 50])

In [ ]:
np.min(a,axis=0)

array([10, 20])

In [ ]:
np.max(a)

60

In [ ]:
np.max(a,axis=0)

array([50, 60])

In [ ]:
np.max(a,axis=1)

array([20, 40, 60])

In [ ]:
np.sum(a)

210

In [ ]:
np.sum(a,axis=0)

array([ 90, 120])

In [ ]:
np.sum(a,axis=1)

array([ 30,  70, 110])

In [ ]:
np.mean(a)

35.0

In [ ]:
np.mean(a,axis=0)

array([30., 40.])

In [ ]:
np.mean(a,axis=1)

array([15., 35., 55.])

In [ ]:
np.median(a)

35.0

In [ ]:
np.median(a,axis=0)

array([30., 40.])

In [ ]:
np.median(a,axis=1)

array([15., 35., 55.])

In [ ]:
np.var(a)

291.6666666666667

In [ ]:
np.var(a,axis=0)

array([266.66666667, 266.66666667])

In [ ]:
np.var(a,axis=1)

array([25., 25., 25.])

In [ ]:
np.std(a)

17.07825127659933

In [ ]:
np.std(a,axis=0)

array([16.32993162, 16.32993162])

In [ ]:
np.std(a,axis=1)

array([5., 5., 5.])